# This is a basic workflow to help you get started with Actions

name: synchronize with svn repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  synchronize:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install subversion
      - name: Install SVN
        run: |
          sudo apt install subversion -y
          svn --version
          
      # Checkout Uni Repo
      - name: Checkout Uni Repo
        env:
          USER: ${{ secrets.USERNAME }}
          PASS: ${{ secrets.PASSWORD }}
        run: |
          mkdir svn
          cd svn
          sudo svn --non-interactive --username $USER --password $PASS checkout https://stud.fh-wedel.de/repos/uebungen/ppws/ppws_26/trunk ./trunk
      
      # Copy Git repo into svn trunk
      - name: Copy GIT to SVN
        run: |
          ls -la ./svn/trunk
          sudo rsync -av --progress ./ svn/trunk --exclude svn
          ls -la ./svn/trunk
          
      - name: Configure SVN Ignore
        run: | 
          cd ./svn/trunk
          ls
          sudo svn propset svn:ignore -F svnignore.txt .
          
      - name: Add and commit all files
        env:
          USER: ${{ secrets.USERNAME }}
          PASS: ${{ secrets.PASSWORD }}
        run: |
          cd ./svn/trunk
          sudo svn cleanup --remove-ignored
          sudo svn add . --force
          sudo svn status
          sudo svn commit -m '${{ github.event.head_commit.message }}' --non-interactive --username $USER --password $PASS ./
