# This is a basic workflow to help you get started with Actions
name: Deploy to k8s

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - $default-branch
    paths:
      - '<path to manifest dir>'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   Deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - uses: azure/setup-kubectl@v4

         - uses: Azure/k8s-set-context@v4
           with:
              kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              manifests: |
                 <path to manifest 1>
                 <path to manifest 2>
